export const BOOKING_TYPE_MATCH = 1000;
export const BOOKING_TYPE_LESSON = 5000;
export const BOOKING_TYPE_TOURNAMENT = 6000;
export const BOOKING_TYPE_MAINTENANCE = 7000;
export const BOOKING_TYPE_RAIN = 7001;
export const BOOKING_TYPE_CLUB_EVENT = 8000;
export const BOOKING_TYPE_MENTORING = 8001;
export const BOOKING_TYPE_JUNIOR_PROGRAM = 8002;
export const BOOKING_TYPE_LADDER = 8003;


